language: node_js
cache:
  yarn: true
  directories:
    - node_modules

node_js:
- '6.9.4'

install:
- yarn install
- npm run lint
- npm run build

deploy:
- provider: npm
  email: onpm@microsoft.com
  skip_cleanup: true
  api_key: $NPM_DEPLOY_TOKEN
  on:
    branch: master
