language: node_js
cache:
  directories:
    - node_modules

node_js:
- '6.9.1'

install:
- npm install
- npm run build

before_deploy:
  - publish-build

deploy:
- provider: npm
  email: onpm@microsoft.com
  skip_cleanup: true
  tag: "beta"
  api_key:
    secure: EbFG4MjhmKoCenjaCqjc0Cs8N+Nun64kNyd56hA5T8AxrGW2kAtxCQ2Lc1Nfls6XHFs4Jj9nk7Sqjt9wgIVn3ZhN5TgMejogl95FHBuWmkoqcGvfSmiCZhXOTon6zveqG7RTq5uLyj2hu4ogNL4mpGj6op8cf3Lg5wqFVN3bP5F2AtIZ5Mt/+Rig1ugKh0vxOCM/hAlSUgX04HUIuAP6FEAX2oUwe2XmdFIWRIK1nyc4Bsbt64tt/aUIW6OYRhoBgjBpEH52Jie7tSV8XJxA/68Lt9izTy6OhCpGv+R3uiasDyoX3r3tCTZKp/guZjM1F+JwdRRDKIwj5MktImwH3V210tgfygqdQi5HYK3C74uzV2ti9nt63FewKpjLTiU3RksXBU3ekoXT63vlp1oBBS4E22qZvXM9OsyhKmeyXBv+qv5L5oVO+dJ98BfHwuR9TzP3wrH2ZCCPM9TTMdT18Vs/ppcZUuL+jyawnewTE6QKVwRZsnz8s3k/1MgN/RgGX+H/KR0+IKG8yya3gbkXBvp5cwxytfO5PY8a0Y01gmxecVuLDniS6/TMxNLlWqAsNqtcCwQypDgKfCl7u45vGTMiV7Vn8ZBVpEEBtAhFq7M7iHbijywy7gDXkcbtvMCAscuWqu8PN2Z8TGEoXPFna+L213ZoqOkPpWO8toAYvDM=
  on:
    repo: OfficeDev/office-js-helpers